<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Olp.Core.ProcessingContracts\Olp.Core.ProcessingContracts.csproj" />
    <ProjectReference Include="..\..\Core\Olp.Core.ProcessingDomain\Olp.Core.ProcessingDomain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Olp.Infrastructure.EventBus.AuthContracts\Olp.Infrastructure.EventBus.AuthContracts.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Olp.Infrastructure.EventBus\Olp.Infrastructure.EventBus.csproj" />
    <ProjectReference Include="..\..\Repositories\Olp.Repositories.ProcessingAbstractions\Olp.Repositories.ProcessingAbstractions.csproj" />
    <ProjectReference Include="..\Olp.Services.ProcessingAbstractions\Olp.Services.ProcessingAbstractions.csproj" />
  </ItemGroup>

</Project>
