<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Olp.ProcessingService.Infrastructure.EntityFramework\Olp.ProcessingService.Infrastructure.EntityFramework.csproj" />
    <ProjectReference Include="..\..\Repositories\Olp.ProcessingService.Repositories.Abstractions\Olp.ProcessingService.Repositories.Abstractions.csproj" />
    <ProjectReference Include="..\..\Repositories\Olp.ProcessingService.Repositories.Implementation\Olp.ProcessingService.Repositories.Implementation.csproj" />
    <ProjectReference Include="..\..\Services\Olp.ProcessingService.Services.Abstractions\Olp.ProcessingService.Services.Abstractions.csproj" />
    <ProjectReference Include="..\..\Services\Olp.ProcessingService.Services.Implementation\Olp.ProcessingService.Services.Implementation.csproj" />
  </ItemGroup>

</Project>
