<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Olp.Infrastructure.EventBus\Olp.Infrastructure.EventBus.csproj" />
    <ProjectReference Include="..\..\Repositories\Olp.Repositories.ProcessingAbstractions\Olp.Repositories.ProcessingAbstractions.csproj" />
    <ProjectReference Include="..\..\Repositories\Olp.Repositories.ProcessingImplementation\Olp.Repositories.ProcessingImplementation.csproj" />
    <ProjectReference Include="..\..\Services\Olp.Services.ProcessingAbstractions\Olp.Services.ProcessingAbstractions.csproj" />
    <ProjectReference Include="..\..\Services\Olp.Services.ProcessingImplementation\Olp.Services.ProcessingImplementation.csproj" />
  </ItemGroup>

</Project>
